apiVersion: v1
kind: Service
metadata:
  name: netflix-app
  labels:
    app: netflix-app
spec:
  selector:
    app: netflix-app
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30007